#!/usr/bin/env python3
"""
01 - Validate a COCO JSON before letting TAO near it. My synthetic dataset and COCO JSON were generated by my own pipeline, this validator checks before TAO training.

Usage:
    python 01_validate_coco.py --json data/synth/annotations/all.json \\
                               --images data/synth/images \\
                               --render-dir /tmp/overlay --render 40

    # Domain-gap check:
    python 01_validate_coco.py --json data/synth/annotations/all.json \\
                               --images data/synth/images \\
                               --compare-to data/real/annotations/all.json
"""
import argparse, json, os, random, sys
from collections import Counter, defaultdict

FAIL, WARN = [], []

def fail(m): FAIL.append(m)
def warn(m): WARN.append(m)

def load(path):
    with open(path) as f:
        return json.load(f)

def validate(coco, image_root, name="dataset"):
    for key in ("images", "annotations", "categories"):
        if key not in coco:
            fail(f"[{name}] missing top-level key '{key}'")
            return None

    imgs, anns, cats = coco["images"], coco["annotations"], coco["categories"]
    print(f"images={len(imgs)}  annotations={len(anns)}  categories={len(cats)}")

    # categories
    cat_ids = sorted(c["id"] for c in cats)
    print("categories:", [(c["id"], c["name"]) for c in cats])
    if 0 in cat_ids:
        fail(f"[{name}] category_id 0 is present. TAO reserves 0 for background; "
             "IDs must start at 1.")
    if cat_ids != list(range(1, len(cat_ids) + 1)):
        fail(f"[{name}] category_ids are not contiguous starting at 1: {cat_ids}")

    # images
    img_by_id, seen_ids, missing_files = {}, set(), 0
    for im in imgs:
        if im["id"] in seen_ids:
            fail(f"[{name}] duplicate image id {im['id']}")
        seen_ids.add(im["id"])
        img_by_id[im["id"]] = im
        for k in ("file_name", "width", "height"):
            if k not in im:
                fail(f"[{name}] image {im.get('id')} missing '{k}'")
        if image_root and missing_files < 10:
            if not os.path.exists(os.path.join(image_root, im.get("file_name", ""))):
                missing_files += 1
                fail(f"[{name}] file not found: {im.get('file_name')}")

    dims = Counter((im.get("width"), im.get("height")) for im in imgs)
    print("image dimensions:", dict(dims))

    # annotations
    ann_ids, per_image, areas, xyxy_suspects, tiny = set(), defaultdict(int), [], 0, 0
    monotonic, n_boxes = 0, 0
    per_class = Counter()

    for a in anns:
        aid = a.get("id")
        if aid in ann_ids:
            fail(f"[{name}] duplicate annotation id {aid}")
        ann_ids.add(aid)

        if a.get("image_id") not in img_by_id:
            fail(f"[{name}] annotation {aid} references unknown image_id {a.get('image_id')}")
            continue

        im = img_by_id[a["image_id"]]
        per_image[a["image_id"]] += 1
        per_class[a.get("category_id")] += 1

        bbox = a.get("bbox")
        if not bbox or len(bbox) != 4:
            fail(f"[{name}] annotation {aid} has malformed bbox: {bbox}")
            continue
        x, y, w, h = bbox

        if w > 0 and h > 0 and (x + w > im["width"] * 1.01 or y + h > im["height"] * 1.01):
            xyxy_suspects += 1
            
        if w > x and h > y:
            monotonic += 1
        n_boxes += 1

        if w <= 0 or h <= 0:
            fail(f"[{name}] annotation {aid} has non-positive w/h: {bbox}")
            continue
        if max(w, h) <= 1.5:
            tiny += 1
        if x < -1 or y < -1:
            warn(f"[{name}] annotation {aid} has negative origin {bbox} (clip to image bounds)")

        if "area" not in a or not a["area"] or a["area"] <= 0:
            fail(f"[{name}] annotation {aid} missing area.")
        elif abs(a["area"] - w * h) > 0.5 * w * h:
            warn(f"[{name}] annotation {aid} area={a['area']} disagrees with w*h={w*h:.0f}")

        if a.get("iscrowd", 0) not in (0, 1):
            fail(f"[{name}] annotation {aid} has invalid iscrowd={a.get('iscrowd')}")
        if a.get("iscrowd", 0) == 1:
            warn(f"[{name}] annotation {aid} has iscrowd=1; it will be ignored by COCOeval")

        areas.append(w * h)

    if xyxy_suspects:
        fail(f"[{name}] {xyxy_suspects} boxes extend past the image edge.")
    if n_boxes >= 20 and monotonic / n_boxes > 0.95:
        fail(f"[{name}] in {monotonic}/{n_boxes} boxes ({monotonic/n_boxes:.0%}) field3>field1 "
             "AND field4>field2.")
    if tiny:
        warn(f"[{name}] {tiny} boxes are <=1.5px. Filter these; they are occlusion artifacts.")

    name_by_id = {c["id"]: c["name"] for c in cats}
    print("instances per class:",
          {name_by_id.get(k, k): v for k, v in sorted(per_class.items())})

    empty = len(imgs) - len(per_image)
    dens = (len(anns) / len(imgs)) if imgs else 0
    print(f"instances/image: mean={dens:.1f}   empty images: {empty} ({empty/max(len(imgs),1):.1%})")
    if empty == 0:
        warn(f"[{name}] no empty frames.")

    stats = area_stats(areas, name)
    return {"areas": areas, "density": dens, "per_class": per_class,
            "name_by_id": name_by_id, "n_images": len(imgs), "stats": stats}

def area_stats(areas, name):
    if not areas:
        return None
    areas = sorted(areas)
    def pct(p): return areas[min(int(p * len(areas)), len(areas) - 1)]
    
    small = sum(1 for a in areas if a < 32 ** 2)
    med = sum(1 for a in areas if 32 ** 2 <= a < 96 ** 2)
    large = sum(1 for a in areas if a >= 96 ** 2)
    n = len(areas)
    print(f"bbox area: p10={pct(.1):.0f}, median={pct(.5):.0f}, p90={pct(.9):.0f} px^2")
    print(f"median equivalent side: {pct(.5)**0.5:.0f} px")
    print(f"size distribution: small={small/n:.1%}, medium={med/n:.1%}, large={large/n:.1%}")
    return {"median": pct(.5), "p10": pct(.1), "p90": pct(.9),
            "small": small / n, "medium": med / n, "large": large / n}

def compare(a, b):
    print(f"DOMAIN GAP: synthetic vs real\n")
    sa, sb = a["stats"], b["stats"]
    if not (sa and sb):
        return
    ratio = sa["median"] / sb["median"]
    side = (ratio ** 0.5)
    print(f"median box area synth={sa['median']:.0f}  real={sb['median']:.0f}  ratio={ratio:.2f}x")
    print(f"median box side synth={sa['median']**.5:.0f}px  real={sb['median']**.5:.0f}px  ({side:.2f}x)")
    print(f"small-object frac synth={sa['small']:.1%}  real={sb['small']:.1%}")
    print(f"instances/image synth={a['density']:.1f}  real={b['density']:.1f}")

    def ratio_of(d):
        tot = sum(d["per_class"].values()) or 1
        return {d["name_by_id"].get(k, k): v / tot for k, v in sorted(d["per_class"].items())}
    print(f"class balance synth={ratio_of(a)}")
    print(f"real ={ratio_of(b)}")

    print()
    if not (0.5 <= side <= 2.0):
        fail("SCALE MISMATCH. Synthetic objects are a very different pixel size from "
             f"real ones ({side:.2f}x on the side).")
    elif not (0.7 <= side <= 1.4):
        warn(f"Object scale differs by {side:.2f}x.")
    else:
        print("OK-object scale distributions are compatible.")

    if a["density"] and b["density"]:
        dr = a["density"] / b["density"]
        if not (0.4 <= dr <= 2.5):
            warn(f"Instance density differs by {dr:.2f}x. The model will learn the wrong "
                 "prior on how many plants to expect per frame.")

def render(coco, image_root, out_dir, k):
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        warn("Pillow not installed.")
        return
    os.makedirs(out_dir, exist_ok=True)
    by_img = defaultdict(list)
    for a in coco["annotations"]:
        by_img[a["image_id"]].append(a)
    names = {c["id"]: c["name"] for c in coco["categories"]}
    colors = {1: (0, 220, 0), 2: (255, 60, 60), 3: (60, 140, 255)}

    for im in random.sample(coco["images"], min(k, len(coco["images"]))):
        p = os.path.join(image_root, im["file_name"])
        if not os.path.exists(p):
            continue
        img = Image.open(p).convert("RGB")
        d = ImageDraw.Draw(img)
        for a in by_img.get(im["id"], []):
            x, y, w, h = a["bbox"]
            c = colors.get(a["category_id"], (255, 255, 0))
            d.rectangle([x, y, x + w, y + h], outline=c, width=3)
            d.text((x + 2, max(0, y - 12)), names.get(a["category_id"], "?"), fill=c)
        img.save(os.path.join(out_dir, os.path.basename(im["file_name"])))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True)
    ap.add_argument("--images", default=None)
    ap.add_argument("--compare-to", default=None, help="second COCO json-the real one")
    ap.add_argument("--compare-images", default=None)
    ap.add_argument("--render-dir", default=None)
    ap.add_argument("--render", type=int, default=0)
    args = ap.parse_args()

    coco = load(args.json)
    a = validate(coco, args.images, os.path.basename(args.json))

    if args.compare_to:
        b = validate(load(args.compare_to), args.compare_images,
                     os.path.basename(args.compare_to))
        if a and b:
            names_a = {c["name"] for c in coco["categories"]}
            names_b = {c["name"] for c in load(args.compare_to)["categories"]}
            if names_a != names_b:
                fail(f"CLASS NAME MISMATCH synth={sorted(names_a)} real={sorted(names_b)}. "
                     "These must be identical strings in identical ID order.")
            compare(a, b)
            
    if args.render and args.render_dir:
        render(coco, args.images, args.render_dir, args.render)

    for w in WARN[:25]:
        print("WARN:", w)
    if len(WARN) > 25:
        print(f"... and {len(WARN)-25} more warnings")
    for f_ in FAIL[:25]:
        print("FAIL:", f_)
    if len(FAIL) > 25:
        print(f"... and {len(FAIL)-25} more failures")
    if FAIL:
        print(f"\n{len(FAIL)} BLOCKING problem.")
        sys.exit(1)
    print("\nPASS.")

if __name__ == "__main__":
    main()
